import { CustomerRecord } from '../types/quote';

/**
 * Default verified Customer Directory extracted from the 'Customers' tab of the Rockwool specification spreadsheet.
 * Contains 106 contractor and commercial customer records with contact, address, telephone, mobile, email, and Technical Sales Manager.
 */
export const DEFAULT_CUSTOMERS: CustomerRecord[] = [
  {
    "id": "cust-1",
    "companyName": "A Thomas Acrylic Render Specialist Ltd",
    "contactPerson": "Mr Adrian Thomas",
    "address": "24 Sunningdale Grdens",
    "cityCounty": "Bogner Regis",
    "postcode": "PO22 9LF",
    "telephone": "01243 830908",
    "mobile": "07968 477565",
    "email": "a-thomas13@sky.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-2",
    "companyName": "B & G Projects",
    "contactPerson": "Mr Steve Kemp-Thacker",
    "address": "32 Rayleigh Drive",
    "cityCounty": "Leigh on Sea, Essex",
    "postcode": "SS9 4JE",
    "telephone": "01702 712461",
    "mobile": "07949 330042",
    "email": "steve@bandgprojects.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-3",
    "companyName": "Build Therm Services Ltd",
    "contactPerson": "Mr Agron Gjoka",
    "address": "Unit 3, Devonshire Business Centre, Cranborne Road",
    "cityCounty": "Potters Bar",
    "postcode": "EN6 3JR",
    "telephone": "0207 124 4025",
    "mobile": "07427 681519",
    "email": "agron.gjoka@buildtherm.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-4",
    "companyName": "Complete Rendering Systems Ltd",
    "contactPerson": "Mr Bradley Hall",
    "address": "28 Bridge Farm, Baracombe Mills",
    "cityCounty": "East Sussex",
    "postcode": "BN8 5BX",
    "telephone": "01273 400424",
    "mobile": "07876 444326",
    "email": "bradley@crsrendering.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-5",
    "companyName": "Eden Facades Ltd",
    "contactPerson": "Mr Anthony Hill",
    "address": "Suite 103, Waterhouse Business Centre, Cromar Way",
    "cityCounty": "Chelmsford, Essex",
    "postcode": "CM1 2QE",
    "telephone": "0845 834 0150",
    "mobile": "07581 285507",
    "email": "tony@edenfacades.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-6",
    "companyName": "Envirorend (SE) Ltd",
    "contactPerson": "Mr Justus Woolford",
    "address": "Envirorend Unit, 7a Crown Yard, Bedgebury Estate",
    "cityCounty": "Goudhurst",
    "postcode": "TN17 2QZ",
    "telephone": "01424 883390",
    "mobile": "07794 940855",
    "email": "justus@envirorendse.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-7",
    "companyName": "Gypcom Ltd",
    "contactPerson": "Mr Mark Jones",
    "address": "Unit 2, G3 Business Park, Dolphin Road",
    "cityCounty": "Shoreham, West Sussex",
    "postcode": "BN43 6AN",
    "telephone": "01273 591725",
    "mobile": "07931 701475",
    "email": "mark@gypcom.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-8",
    "companyName": "Eco-Rend South East Ltd",
    "contactPerson": "Mr Scott Watson",
    "address": "Unit 1a, Deanland Business Park, Deanland Road",
    "cityCounty": "Golden Cross, East Sussex",
    "postcode": "CN27 3RP",
    "telephone": "",
    "mobile": "07989 954497",
    "email": "enquiries@eco-rend.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-9",
    "companyName": "P3 Projection Coatings (UK) Ltd",
    "contactPerson": "Mr Jason Smith",
    "address": "Unit 7, The Woods Building, The Wharf",
    "cityCounty": "Midhurst, West Sussex",
    "postcode": "GU29 9PX",
    "telephone": "0870 803 4360",
    "mobile": "07973 728929",
    "email": "jason@p3.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-10",
    "companyName": "Pioneer Wall Cladding & Building Insulation Ltd",
    "contactPerson": "Mr Andrei Tartza",
    "address": "10 Oak Lodge Close",
    "cityCounty": "Hersham, Surrey",
    "postcode": "KT12 5YQ",
    "telephone": "01932 221209",
    "mobile": "07538 636661",
    "email": "andre.tartza@pioneerinsulation.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-11",
    "companyName": "Regency Plastering",
    "contactPerson": "Mr Paul Brown",
    "address": "Pinden End Farm, Canada Farm Road",
    "cityCounty": "Dartford, Kent",
    "postcode": "DA2 8EA",
    "telephone": "01474 707255",
    "mobile": "07970 270983",
    "email": "pbrown@rvpl.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-12",
    "companyName": "Rendco Rendering Ltd",
    "contactPerson": "Mr Gary Redman",
    "address": "58 Overhill",
    "cityCounty": "Southwick, Sussex",
    "postcode": "BN42 4WJ",
    "telephone": "",
    "mobile": "07801 552663",
    "email": "info@rendco.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-13",
    "companyName": "Retrofit UK Ltd",
    "contactPerson": "Mr Nick Stevens",
    "address": "Unit K, Broad Lane Industrial Estate, Broad Lane",
    "cityCounty": "Cambridge",
    "postcode": "CB24 8SW",
    "telephone": "01954 252177",
    "mobile": "07713 075595",
    "email": "nick.stevens@retrofituk.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-14",
    "companyName": "South East Render Systems",
    "contactPerson": "Mr Stuart Wickens",
    "address": "69 Ferndale Road",
    "cityCounty": "Gravesend, Kent",
    "postcode": "DA12 5AE",
    "telephone": "01474 746393",
    "mobile": "07876 521445",
    "email": "southeastrendersystems@gmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-15",
    "companyName": "Specialist Rendering Services",
    "contactPerson": "Mr Jason McCarroll",
    "address": "7 Ballyknockan Road",
    "cityCounty": "Saintfield, Co Down",
    "postcode": "BT24 7HQ",
    "telephone": "02890 813429",
    "mobile": "07947 832569",
    "email": "admin@specialistrenderingservices.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-16",
    "companyName": "Wall Solutions Ltd",
    "contactPerson": "Mr Darren Parker",
    "address": "Suite 12, Webb House, 20 Bridge Road",
    "cityCounty": "Park Gate, Hampshire",
    "postcode": "SO31 7GE",
    "telephone": "01329 312014",
    "mobile": "07786 172511",
    "email": "darrenparker@wallsolutions.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-17",
    "companyName": "Wallcoatings Ltd",
    "contactPerson": "Mr Bill Blackburn",
    "address": "Unit A5, Albion Building, Daeddalus Park, Daeddalus Drive",
    "cityCounty": "Lee on the Solent",
    "postcode": "PO13 9FX",
    "telephone": "01329 237110",
    "mobile": "07977 263625",
    "email": "bill.blackburn@live.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-18",
    "companyName": "Walltec Ltd",
    "contactPerson": "Mr Adam Griffin",
    "address": "Unit 89, The Oaks, Manston Business Park",
    "cityCounty": "Ramsgate, Kent",
    "postcode": "CT12 5FN",
    "telephone": "01843 824944",
    "mobile": "07388 027137",
    "email": "adam@walltecltd.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-19",
    "companyName": "Teampol Ltd",
    "contactPerson": "Mr Tomasz Talaska",
    "address": "17 Lakeside Park, Neptune Close, Medway City Estate",
    "cityCounty": "Rochester, Kent",
    "postcode": "ME2 4LT",
    "telephone": "01634 830220",
    "mobile": "07877 289679",
    "email": "t.talaska@teampol.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-20",
    "companyName": "AT Jones & Son Ltd",
    "contactPerson": "Mr Adam Lee",
    "address": "6 The Potteries",
    "cityCounty": "Fareham, Hampshire",
    "postcode": "PO16 7ET",
    "telephone": "01329 287891",
    "mobile": "07772 539559",
    "email": "adamlee@atjones.net",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-21",
    "companyName": "Apex Facades Ltd",
    "contactPerson": "Mr Adrian Brunger",
    "address": "Suite 2028, Kent Space Ashford, Wotton Road",
    "cityCounty": "Ashford, Kent",
    "postcode": "TN23 6LN",
    "telephone": "01233 229496",
    "mobile": "07711 656161",
    "email": "adrian@apexfacades.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-22",
    "companyName": "Hillier Marsden Ltd",
    "contactPerson": "Mr Bill Marsden",
    "address": "Unit 42 Murrell Green Business Park, London Road",
    "cityCounty": "Hook, Hampshire",
    "postcode": "RG27 9GR",
    "telephone": "01252 302322",
    "mobile": "07796 330066",
    "email": "bill@hilliermarsden.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-23",
    "companyName": "Insulated Render Systems Ltd",
    "contactPerson": "Mr Daran Coney",
    "address": "St Stephens Cottage, 22 Western Road",
    "cityCounty": "Littlehampton, West Sussex",
    "postcode": "BN17 5PG",
    "telephone": "",
    "mobile": "07813 160272",
    "email": "insulatedrendersystems@yahoo.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-24",
    "companyName": "Eeles Plastering & Drylining Ltd",
    "contactPerson": "Mr Tony Eeles",
    "address": "28 Chipendayle Drive, Harrietsham",
    "cityCounty": "Maidstone, Kent",
    "postcode": "ME17 1AD",
    "telephone": "01622 851795",
    "mobile": "07952 763418",
    "email": "tony@eelesplastering.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-25",
    "companyName": "Facade Concepts Ltd",
    "contactPerson": "Mr Keith Ballard",
    "address": "1 Kennett Road",
    "cityCounty": "Dartford, Kent",
    "postcode": "DA1 4QN",
    "telephone": "01322 408821",
    "mobile": "",
    "email": "keith@facadeconcepts.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-26",
    "companyName": "Total Render Systems Ltd",
    "contactPerson": "Mr Richard Nurse",
    "address": "77 Baytree Road",
    "cityCounty": "Weston Super Mare, North Somerset",
    "postcode": "BS22 8HW",
    "telephone": "",
    "mobile": "07803 957972",
    "email": "richard@renderservices.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-27",
    "companyName": "Bobut Builders Ltd",
    "contactPerson": "Mr George Bobut",
    "address": "Unit B7, Pheonix Industrial Estate, Rosslyn Crescent",
    "cityCounty": "Harrow",
    "postcode": "HA1 2SP",
    "telephone": "",
    "mobile": "07919 575221",
    "email": "george@bobut-rendering.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-28",
    "companyName": "Wells & Munday",
    "contactPerson": "Mr David North",
    "address": "92 Winslow Road",
    "cityCounty": "Wingrave, Aylesbury, Bucks",
    "postcode": "HP22 4QB",
    "telephone": "",
    "mobile": "07778 787724",
    "email": "wells_munday@hotmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-29",
    "companyName": "SC Rendering",
    "contactPerson": "Mr Sam Moss",
    "address": "14 High Street",
    "cityCounty": "East Grinstead, West Sussex",
    "postcode": "RH19 3AW",
    "telephone": "",
    "mobile": "07834 416788",
    "email": "sc_rendering@icloud.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-30",
    "companyName": "Eco-Insulation Home Ltd",
    "contactPerson": "Mr Nick Sula",
    "address": "58 Mayfield Avenue",
    "cityCounty": "Southgate, London",
    "postcode": "N14 6DU",
    "telephone": "",
    "mobile": "07852 869994",
    "email": "admin@eco-insulationhome.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-31",
    "companyName": "MH Goldsmith & Sons Ltd",
    "contactPerson": "Mr Neil Kent",
    "address": "19-21a Station Road",
    "cityCounty": "Knebworth, Herts",
    "postcode": "SG3 6AP",
    "telephone": "",
    "mobile": "07825 569729",
    "email": "neil@mhgservices.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-32",
    "companyName": "EJL Plastering & Rendering Ltd",
    "contactPerson": "Mr Dan Larder",
    "address": "49 Fir Copse Road",
    "cityCounty": "Widley",
    "postcode": "PO7 5HZ",
    "telephone": "",
    "mobile": "07944 397356",
    "email": "ejl.plastering@gmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-33",
    "companyName": "Lawtech Group Ltd",
    "contactPerson": "Mr Alex Coombs",
    "address": "Unit 11-12 Lakeside Park, Medway City Estate, Neptune Close",
    "cityCounty": "Rochester",
    "postcode": "ME2 4LT",
    "telephone": "01634 290500",
    "mobile": "07964 688548",
    "email": "alex.coombs@lawtechgroup.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-34",
    "companyName": "EWIS",
    "contactPerson": "Mr Paul Jones",
    "address": "Energy House, Grandstand Road",
    "cityCounty": "Hereford",
    "postcode": "HR4 9NH",
    "telephone": "",
    "mobile": "07921 493292",
    "email": "p.jones@ewis-ukltd.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-35",
    "companyName": "Renderline Ltd",
    "contactPerson": "Mr Pawel Ptak",
    "address": "Unit 5, Greenhill House, Greenhill Crescent",
    "cityCounty": "Watford",
    "postcode": "WD18 8JA",
    "telephone": "",
    "mobile": "07749 639407",
    "email": "info@renderline.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-36",
    "companyName": "Green Facades",
    "contactPerson": "Mr Lyle House",
    "address": "371 Woolwich Road",
    "cityCounty": "London",
    "postcode": "SE7 7AJ",
    "telephone": "",
    "mobile": "07309 670933",
    "email": "lyle@greenfacades.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-37",
    "companyName": "AMJ Contracts Ltd",
    "contactPerson": "Mr Luke Cooper",
    "address": "78 Dallinger Road",
    "cityCounty": "London",
    "postcode": "SE12 0TH",
    "telephone": "020 3633 1074",
    "mobile": "07908 355640",
    "email": "luke.cooper@amjcontracts.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-38",
    "companyName": "Thermoclad Ltd",
    "contactPerson": "Mr Ronnie Sopjani",
    "address": "31a Frogmore, Park Street",
    "cityCounty": "St Albans",
    "postcode": "AL2 2NG",
    "telephone": "",
    "mobile": "07974 868511",
    "email": "agron.sopjani@thermoclad.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-39",
    "companyName": "Fullers Plastering",
    "contactPerson": "Mr James Corlett",
    "address": "Unit 12 Seaview Way, Woodingdean Business Park",
    "cityCounty": "Brighton",
    "postcode": "BN2 6NX",
    "telephone": "01273 686368",
    "mobile": "07776 205918",
    "email": "james@fullers-plastering.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-40",
    "companyName": "Apex Facades",
    "contactPerson": "Mr Adrian Brunger",
    "address": "Suite 2028, Kingsnorth Industrial Estate, Kent Space, Wotton Road",
    "cityCounty": "Ashford",
    "postcode": "TN23 6LN",
    "telephone": "01233 229496",
    "mobile": "07711 656161",
    "email": "adrian@apexfacades.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-41",
    "companyName": "Macai Limited",
    "contactPerson": "Mr Nigel Hawes",
    "address": "106 Down Street",
    "cityCounty": "West Moseley, Surrey",
    "postcode": "KT8 2TA",
    "telephone": "020 8941 2442",
    "mobile": "07816 659710",
    "email": "n.hawes@macai-limited.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-42",
    "companyName": "Insa Rend",
    "contactPerson": "Mr Dan Wilson",
    "address": "23a Wilbury Grove",
    "cityCounty": "Hove",
    "postcode": "BN3 3JQ",
    "telephone": "01273 321560",
    "mobile": "07870 678874",
    "email": "insarend@gmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-43",
    "companyName": "Eco Facades Ltd",
    "contactPerson": "Mr Lee Williams",
    "address": "106 Sparrows Herne",
    "cityCounty": "Basildon",
    "postcode": "SS16 5EU",
    "telephone": "01268 280676",
    "mobile": "07805 358609",
    "email": "lee@ecofacadesltd.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-44",
    "companyName": "Square 1 Architecture",
    "contactPerson": "Mr Andrew Downer",
    "address": "Unit 3, Sarisbury Buildings, 172 Bridge Street, Sarisbury",
    "cityCounty": "Southampton",
    "postcode": "SA31 7EH",
    "telephone": "01489 583371",
    "mobile": "07949 050099",
    "email": "andrew.downer@square-1.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-45",
    "companyName": "Wells & Munday",
    "contactPerson": "Mr David North",
    "address": "Winslow Road, Wingrave",
    "cityCounty": "Aylesbury",
    "postcode": "HP22 4QB",
    "telephone": "",
    "mobile": "07770 787724",
    "email": "wells_munday@hotmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-46",
    "companyName": "S C Rendering",
    "contactPerson": "Mr Sam Moss",
    "address": "14 High Street",
    "cityCounty": "East Grinstead, West Sussex",
    "postcode": "RH19 3AW",
    "telephone": "",
    "mobile": "07834 416788",
    "email": "Sc_rendering@icloud.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-47",
    "companyName": "DAB Services",
    "contactPerson": "Mr Dean Bowles",
    "address": "43 Alderbrook Close",
    "cityCounty": "Crowborough",
    "postcode": "TN6 3DL",
    "telephone": "",
    "mobile": "07568 141799",
    "email": "dean.dab@yahoo.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-48",
    "companyName": "Cornerstone",
    "contactPerson": "Mr Joel Mullin",
    "address": "Unit 18, Glenmore Business Park",
    "cityCounty": "Waterbeach, Cambridge",
    "postcode": "CB25 9FX",
    "telephone": "",
    "mobile": "07392 789256",
    "email": "joel.cornerstonelimited.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-49",
    "companyName": "Hamilton (Building Contractors) Ltd",
    "contactPerson": "Mr Danny Mackie",
    "address": "7A Sapper Jordan Rossi Park, Baildon",
    "cityCounty": "Shipley, West Yorkshire",
    "postcode": "BD17 7AX",
    "telephone": "01274 666166",
    "mobile": "07900 741341",
    "email": "dmackie@hamiltonfirst.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-50",
    "companyName": "Novo Facades",
    "contactPerson": "Mr Adam Guina",
    "address": "74 Broadway",
    "cityCounty": "Pereborough",
    "postcode": "PE1 1SU",
    "telephone": "",
    "mobile": "07720 966842",
    "email": "adam@novofacades.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-51",
    "companyName": "OCL Facades",
    "contactPerson": "Mr Richie Miller",
    "address": "9 Argent Court, Southfields Business Park",
    "cityCounty": "Laindon, Essex",
    "postcode": "SS15 6TH",
    "telephone": "",
    "mobile": "07794 049903",
    "email": "r.miller@oclfacades.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-52",
    "companyName": "Cladding UK Ltd",
    "contactPerson": "Mr Ian Goodall",
    "address": "12 London Road",
    "cityCounty": "Stanford Le Hope",
    "postcode": "SS17 0LL",
    "telephone": "",
    "mobile": "07966 420922",
    "email": "iangoodall@btconnect.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-53",
    "companyName": "Primers Coatings Services Ltd",
    "contactPerson": "Mr Julian Turner",
    "address": "Unit 5, 186 St Albans Road",
    "cityCounty": "Watford",
    "postcode": "WD24 4AS",
    "telephone": "",
    "mobile": "07572 445761",
    "email": "julian@primars.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-54",
    "companyName": "All Kent Plastering",
    "contactPerson": "Mr Paul Chapman",
    "address": "6 Hero Walk",
    "cityCounty": "Rochester, Kent",
    "postcode": "ME1 2UZ",
    "telephone": "",
    "mobile": "07793 650280",
    "email": "paul.chapman68@hotmail.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-55",
    "companyName": "PJ Mear",
    "contactPerson": "Mr Leo Burdett",
    "address": "Huntingdon Business Centre, Blackstone Road",
    "cityCounty": "Huntingdon, Cambridgeshire",
    "postcode": "PE29 6EF",
    "telephone": "01480 431117",
    "mobile": "07557 687474",
    "email": "leoburdett@pjmear.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-56",
    "companyName": "Malden Renders & Finishes",
    "contactPerson": "Mr Lee Chapman",
    "address": "32 Station Avenue",
    "cityCounty": "Caterham, Surrey",
    "postcode": "CR3 6LB",
    "telephone": "020 8686 0057",
    "mobile": "07979 746542",
    "email": "lee.chapman@m-r-f.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-57",
    "companyName": "GDG Cladding & Construction",
    "contactPerson": "Mr John Dunsmuir",
    "address": "53a Great North Road",
    "cityCounty": "Welwyn Garden City, Hertfordshire",
    "postcode": "AL8 7TL",
    "telephone": "01707 323209",
    "mobile": "07972 113632",
    "email": "john.dunsmuir@gdgcladding.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-58",
    "companyName": "Sudbury Plastering Services Ltd",
    "contactPerson": "Mr Conor Duffy",
    "address": "Ground Floor College House, 17 King Edwards Road",
    "cityCounty": "Ruislip, Middlesex",
    "postcode": "HA4 7AE",
    "telephone": "01895 632806",
    "mobile": "",
    "email": "conor@sudburyplastering.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-59",
    "companyName": "Everrend Ltd",
    "contactPerson": "Mr Mike Fawcett",
    "address": "3 Purbeck Drive",
    "cityCounty": "Fareham",
    "postcode": "PO14 1RY",
    "telephone": "",
    "mobile": "07717 337309",
    "email": "mike.fawcett@everrend.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-60",
    "companyName": "AMJ Contracts Ltd",
    "contactPerson": "Mr Luke Cooper",
    "address": "78 Dallinger Road",
    "cityCounty": "London",
    "postcode": "SE12 0TH",
    "telephone": "020 3633 1074",
    "mobile": "07908 355640",
    "email": "luke.cooper@amjcontracts.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-61",
    "companyName": "Southern Maze Ltd",
    "contactPerson": "Mr George Albaster",
    "address": "Augustine Road, Minster On Sea",
    "cityCounty": "Sheerness",
    "postcode": "ME12 2LZ",
    "telephone": "01622 939180",
    "mobile": "07496 724856",
    "email": "george@southernmazeltd.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-62",
    "companyName": "Chiltern Contracts",
    "contactPerson": "Mr Harrison Wood",
    "address": "Business Design Centre, 52 Upper St",
    "cityCounty": "London",
    "postcode": "N1 0QH",
    "telephone": "020 3887 7693",
    "mobile": "07772 937539",
    "email": "harrison@chilterncontracts.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-63",
    "companyName": "LB Plastering",
    "contactPerson": "Mr Liam Barham",
    "address": "105 Bayford Road",
    "cityCounty": "Littlehampton",
    "postcode": "BN17 5HW",
    "telephone": "",
    "mobile": "07772 937539",
    "email": "liamstewartbarham@icloud.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-64",
    "companyName": "SJW Rendering Ltd",
    "contactPerson": "Mr Tony King",
    "address": "Four Winds, Parsonage Lane",
    "cityCounty": "Westfield",
    "postcode": "TN35 4SH",
    "telephone": "",
    "mobile": "07894 831097",
    "email": "tony@sjwrendering.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-65",
    "companyName": "Everdell Plastering",
    "contactPerson": "Mr Marcus Everdell",
    "address": "13 Rose Walk",
    "cityCounty": "Seaford",
    "postcode": "BN25 3DH",
    "telephone": "",
    "mobile": "07788 487503",
    "email": "meverdell@gmail.com",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-66",
    "companyName": "Gypsum Limited",
    "contactPerson": "Mr David Wilson",
    "address": "21b Picton House, Hussar Court",
    "cityCounty": "Waterlooville",
    "postcode": "PO7 7SQ",
    "telephone": "02392 240 000",
    "mobile": "07803 378436",
    "email": "david@gypsumltd.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-67",
    "companyName": "MRG Render Systems Ltd",
    "contactPerson": "Mr Mark Gregory",
    "address": "4 Wellington Street",
    "cityCounty": "Thame, Oxfordshire",
    "postcode": "OX9 3BN",
    "telephone": "",
    "mobile": "07485 515398",
    "email": "mark@mrgrendersystems.co.uk",
    "technicalSalesManager": "Paul Dale"
  },
  {
    "id": "cust-68",
    "companyName": "Hamilton (Building Contractors) Ltd",
    "contactPerson": "Mr Danny Mackie",
    "address": "Commerce Court, Challenge Way, Cutler Heights",
    "cityCounty": "Bradford",
    "postcode": "BD4 8NW",
    "telephone": "01274 666166",
    "mobile": "07900 741341",
    "email": "dmackie@hamiltonfirst.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-69",
    "companyName": "Eden Facades",
    "contactPerson": "Mr Tony Hill",
    "address": "Alexander House, Christy Close",
    "cityCounty": "Basildon, Essex",
    "postcode": "SS15 6TL",
    "telephone": "01268 744199",
    "mobile": "",
    "email": "tony@edenfacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-70",
    "companyName": "P J Mear",
    "contactPerson": "Mr Nick Stevens",
    "address": "10d Aspen House, Vantage Park, Washingley Road",
    "cityCounty": "Huntingdon",
    "postcode": "PE29 6SR",
    "telephone": "01480 431117",
    "mobile": "0771 3075595",
    "email": "nickstevens@pjmear.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-71",
    "companyName": "Brel Facades",
    "contactPerson": "Mr Lyle House",
    "address": "Units 5-8, 50 River Gardens Walk",
    "cityCounty": "London",
    "postcode": "SE10 0UB",
    "telephone": "0208 858 2030",
    "mobile": "07309 670933",
    "email": "lyle@greenfacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-72",
    "companyName": "EK Facades",
    "contactPerson": "Mr Marc Barulis",
    "address": "3 Sandpit Road",
    "cityCounty": "Dartford",
    "postcode": "DA1 5BU",
    "telephone": "0208 050 0235",
    "mobile": "07958 961 529",
    "email": "Marc@ekfacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-73",
    "companyName": "Thermoclad Limited",
    "contactPerson": "Mr Mo Alzubaidi",
    "address": "5, Oaks Court, Warwick Road",
    "cityCounty": "Borehamwood",
    "postcode": "WD6 1GS",
    "telephone": "0208 191 1150",
    "mobile": "07956 672 893",
    "email": "Mohammed.alzubaidi@thermoclad.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-74",
    "companyName": "Envirorend SE Limited",
    "contactPerson": "Mr Rob Pearson",
    "address": "7a Crown Yard, Bedgebury Estate, Bedgebury Road",
    "cityCounty": "Goudhurst",
    "postcode": "TN17 2QZ",
    "telephone": "01580 848600",
    "mobile": "07715 219117",
    "email": "rob.pearson@envirorendse.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-75",
    "companyName": "MK Facades Limited",
    "contactPerson": "Mr Jack Maidment",
    "address": "Allport House, Princes Street",
    "cityCounty": "Southampton",
    "postcode": "SO14 5RP",
    "telephone": "02380 016777",
    "mobile": "07789 879446",
    "email": "jack.maidment@mkfacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-76",
    "companyName": "Craft Interiors Limited",
    "contactPerson": "Mr Emil Kot",
    "address": "1 Mount Place, Acton",
    "cityCounty": "London",
    "postcode": "W3 9DH",
    "telephone": "",
    "mobile": "07930 920 777",
    "email": "e.kot@craft-facades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-77",
    "companyName": "Square 1 Facades",
    "contactPerson": "Mr Andrew Downer",
    "address": "Unit 2, Hedge End Business Centre, Botley Road",
    "cityCounty": "Hedge End",
    "postcode": "SO30 2AU",
    "telephone": "02380 016207",
    "mobile": "07949 050 099",
    "email": "andrew.downer@square-1.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-78",
    "companyName": "OCL London",
    "contactPerson": "Mr Tommy Occelshaw",
    "address": "Chester House, Chester Hall Lane",
    "cityCounty": "Basildon, Essex",
    "postcode": "SS14 3BG",
    "telephone": "01268 407940",
    "mobile": "07969 174656",
    "email": "tommy.occleshaw@ocl.london",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-79",
    "companyName": "Southern Maze Ltd",
    "contactPerson": "Mr George Alabaster",
    "address": "C/o Tudor Lodge, Augustine Road, Minster on Sea",
    "cityCounty": "Sheerness, Kent",
    "postcode": "ME12 2LZ",
    "telephone": "01622 939181",
    "mobile": "07496 724 856",
    "email": "george@southernmazeltd.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-80",
    "companyName": "Eco Facades Ltd",
    "contactPerson": "Mr Mark Williams",
    "address": "106 Sparrows Herne",
    "cityCounty": "Basildon, Essex",
    "postcode": "SS16 5EU",
    "telephone": "01268 280676",
    "mobile": "07973 672457",
    "email": "mark@ecofacadesltd.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-81",
    "companyName": "RJ Dean Plasterers Limit",
    "contactPerson": "Mr Sam Dean",
    "address": "Unit 7, West Road, Ransomes Europark",
    "cityCounty": "Ipswich",
    "postcode": "IP3 9FE",
    "telephone": "01473 290000",
    "mobile": "",
    "email": "Sam.dean@rjdeanplasterers.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-82",
    "companyName": "Lawtech Group",
    "contactPerson": "Mr Alex Coombs",
    "address": "8 Ambley Green, Gillingham Business Park",
    "cityCounty": "Gillingham, Kent",
    "postcode": "ME8 0NJ",
    "telephone": "01634 290500",
    "mobile": "07964 688548",
    "email": "Alexander.Coombs@lawtechgroup.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-83",
    "companyName": "FCS Facades",
    "contactPerson": "Mr Darrell Ditchburn",
    "address": "The Flint Barn, Glovers Close",
    "cityCounty": "Biggin Hill, Kent",
    "postcode": "TN16 3GA",
    "telephone": "0203 0115 810",
    "mobile": "",
    "email": "d.ditchburn@fcsfacades.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-84",
    "companyName": "Zeno Facades",
    "contactPerson": "Mr Greg Beaver",
    "address": "Zeno House, Osier Way",
    "cityCounty": "Olney",
    "postcode": "MK46 5FP",
    "telephone": "01234 943745",
    "mobile": "",
    "email": "greg@zenofacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-85",
    "companyName": "Church Insulation Ltd",
    "contactPerson": "Mr Mike Church",
    "address": "17 Chapmans Drive",
    "cityCounty": "Great Cambourne, Cambridge",
    "postcode": "CB23 6AD",
    "telephone": "",
    "mobile": "07794 095203",
    "email": "Michael@churchinsulationltd.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-86",
    "companyName": "GDP Contracts",
    "contactPerson": "Marie",
    "address": "Unit 4B, Upton Business Park",
    "cityCounty": "Upton Upon Severn, Worcestershire",
    "postcode": "WR8 0SW",
    "telephone": "01684 591431",
    "mobile": "",
    "email": "marie@gdpcontractsltd.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-87",
    "companyName": "Kennet Construction",
    "contactPerson": "John Bishop",
    "address": "Enfield Works, Upper Westwood",
    "cityCounty": "Bradford Upon Avon",
    "postcode": "BA15 2DH",
    "telephone": "01225 864181",
    "mobile": "",
    "email": "jbishop@kennetconstruction.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-88",
    "companyName": "TGM Contractors Ltd",
    "contactPerson": "Sean McCullagh",
    "address": "A11 Bell Lane Office Village, Bell Lane",
    "cityCounty": "Little Chalfont",
    "postcode": "HP6 6FA",
    "telephone": "01753 888031",
    "mobile": "",
    "email": "sean@tgmcontractors.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-89",
    "companyName": "DS Render Solutions",
    "contactPerson": "Daniel Istrate",
    "address": "19 Beaufort Gardens",
    "cityCounty": "London",
    "postcode": "NW4 3QN",
    "telephone": "",
    "mobile": "07877 622166",
    "email": "ds.rendersolutions@yahoo.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-90",
    "companyName": "V&L Construct Ltd",
    "contactPerson": "Vlad Llisei",
    "address": "1 Essoldo Way",
    "cityCounty": "London",
    "postcode": "HA8 5NU",
    "telephone": "",
    "mobile": "07401 560480",
    "email": "vlad.vlconstruct@yahoo.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-91",
    "companyName": "RCA Facades Systems Solutions LTD",
    "contactPerson": "Constantin Rebrisorean",
    "address": "31 Woburn Close",
    "cityCounty": "London",
    "postcode": "SE28 8QZ",
    "telephone": "",
    "mobile": "07881 6646631",
    "email": "rcafacades@mail.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-92",
    "companyName": "RKC",
    "contactPerson": "Colin Newton",
    "address": "RKC House, Forstal Business Park, Maidstone Road",
    "cityCounty": "Paddock Wood",
    "postcode": "TN12 6PY",
    "telephone": "",
    "mobile": "07921 831926",
    "email": "colin@rkc.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-93",
    "companyName": "XPERT Construction",
    "contactPerson": "Adriana Negoita",
    "address": "63-66 Hatton Gardens, Fifth Floor, Suite 23",
    "cityCounty": "London",
    "postcode": "EC1N 8LE",
    "telephone": "0203 813 4084",
    "mobile": "",
    "email": "Adriana@xprt-construction.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-94",
    "companyName": "Regency Facades",
    "contactPerson": "Dave Hellyar",
    "address": "Unit 11, Mortimers Trading Estate, Romsey Road",
    "cityCounty": "Ower, Hampshire",
    "postcode": "SO51 6AL",
    "telephone": "02382 000077",
    "mobile": "07766 884232",
    "email": "dave@regencyfacades.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-95",
    "companyName": "Dmitro Development Ltd",
    "contactPerson": "Mara Reut",
    "address": "Unit 2, Oasthouse Way",
    "cityCounty": "Orpington, Kent",
    "postcode": "BR5 3PT",
    "telephone": "01689 834847",
    "mobile": "",
    "email": "info@dmitrodev.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-96",
    "companyName": "Gypcom Limited",
    "contactPerson": "Matt Ashton",
    "address": "Unit 2, G3 Business Park, Dolphin Road",
    "cityCounty": "Shoreham-by-Sea, East Sussex",
    "postcode": "",
    "telephone": "01273 591725",
    "mobile": "",
    "email": "matt@gypcom.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-97",
    "companyName": "Horizon Facades Ltd",
    "contactPerson": "Niall Hawkins",
    "address": "Manor of Groves, High Wych",
    "cityCounty": "Hertfordshire",
    "postcode": "CM21 0JU",
    "telephone": "",
    "mobile": "",
    "email": "niall@horizonfacades.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-98",
    "companyName": "Keystone Roofing & Facades Ltd",
    "contactPerson": "Nick Duddell",
    "address": "Unit 5, Minton Business Centre, Main Road, Far Cotton",
    "cityCounty": "Northampton",
    "postcode": "NN4 8ES",
    "telephone": "01604 877581",
    "mobile": "",
    "email": "nick.duddell@keystoneroofing.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-99",
    "companyName": "Starfish Construction",
    "contactPerson": "Robert Morgan",
    "address": "60 Cannon Street",
    "cityCounty": "London",
    "postcode": "EC4N 6NP",
    "telephone": "01698 833 556",
    "mobile": "7957108162",
    "email": "rmorgan@starfishltd.com",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-100",
    "companyName": "Teampol",
    "contactPerson": "Scott Millins",
    "address": "8 Victory Park, Trident Close",
    "cityCounty": "Medway City Estate",
    "postcode": "ME2 4ER",
    "telephone": "01634 730 773",
    "mobile": "07834 167661",
    "email": "s.millins@teampol.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-101",
    "companyName": "Stoneguard Projects Limited",
    "contactPerson": "Tony Nolan",
    "address": "726 Field End Road",
    "cityCounty": "Ruislip",
    "postcode": "HA4 0QP",
    "telephone": "020 8902 7870",
    "mobile": "",
    "email": "tony@stoneguard.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-102",
    "companyName": "Stanmore",
    "contactPerson": "Saravanan Loganathan",
    "address": "Stanmore House, Gyproc Business Park, Church Manorway",
    "cityCounty": "Erith, Kent",
    "postcode": "DA8 1DE",
    "telephone": "01322 446446",
    "mobile": "",
    "email": "Saravanan.Loganathan@stanmore.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-103",
    "companyName": "Gypcraft Drylining Contractors Limited",
    "contactPerson": "Nicky Lewis",
    "address": "Unit F15, Birch House, Birch Walk",
    "cityCounty": "Erith, Kent",
    "postcode": "DA8 1QX",
    "telephone": "01322 448856",
    "mobile": "",
    "email": "Nicky.Lewis@gypcraftltd.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-104",
    "companyName": "H1 Interiors",
    "contactPerson": "Phil Moriarty",
    "address": "167-169 Great Portland Street, 5th Floor",
    "cityCounty": "London",
    "postcode": "W1W 5PF",
    "telephone": "",
    "mobile": "07894 824232",
    "email": "philip@h1interiors.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-105",
    "companyName": "CSW Cladding Ltd",
    "contactPerson": "Sam Keyte",
    "address": "Rownhams House",
    "cityCounty": "Rownhams, Southampton",
    "postcode": "SO16 8LS",
    "telephone": "02382 148588",
    "mobile": "",
    "email": "sam@cswcladding.co.uk",
    "technicalSalesManager": "Toby Britton"
  },
  {
    "id": "cust-106",
    "companyName": "Interior Partnerships Limited",
    "contactPerson": "Sebastian Bivolaru",
    "address": "The Forge, Heron Hill",
    "cityCounty": "Belvedere",
    "postcode": "DA17 5ER",
    "telephone": "0208 294 7070",
    "mobile": "",
    "email": "sebastian@interiorpartnerships.com",
    "technicalSalesManager": "Toby Britton"
  }
];
